version: '3.9'
services:
  db:
    image: postgres
#    restart: always
    environment:
      POSTGRES_DB: chargers
      POSTGRES_USER: uros
      POSTGRES_PASSWORD: uros
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
